apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80        # Exposed port for external access
      targetPort: 3000 # Port in the container to forward traffic to
  type: LoadBalancer

